version: '3.8'

services:
  dashboard:
    build: .
    ports:
      - "8050:8050"
    volumes:
      - .:/app
    environment:
      - USE_TESTNET=true
    env_file:
      - .env
    command: python examples/dashboard_example.py
    restart: unless-stopped

  # Serviço para desenvolvimento com hot-reload
  dev:
    build: .
    ports:
      - "8050:8050"
    volumes:
      - .:/app
    environment:
      - USE_TESTNET=true
      - PYTHONPATH=/app
    env_file:
      - .env
    command: uvicorn src.web.app:app --host 0.0.0.0 --port 8050 --reload
    restart: unless-stopped

  # Serviço para testes
  test:
    build: .
    volumes:
      - .:/app
    environment:
      - USE_TESTNET=true
      - PYTHONPATH=/app
    command: pytest
    profiles:
      - test